version: ci.0.0-{build}
image: Ubuntu1804

max_jobs: 1

build:
  verbosity: minimal

branches:
  only:
    - master
    - dev

before_build:
  - sudo apt-get update
  - sudo apt-get install git build-essential cmake -y
  - cmake .

build_script:
  - make

notifications:
  - provider: Email
    to:
      - gloomyghost@gloomyghost.com
    subject: 'SinsyNG Build {{status}}'
    message: "{{message}}, {{commitId}}, ..."
    on_build_status_changed: true