version: ci.0.0-{build}
image: Ubuntu1804

max_jobs: 1

build:
  verbosity: minimal

branches:
  only:
    - master
    - dev

before_build:
  - sudo apt-get update
  - sudo apt-get install git build-essential cmake -y
  - cmake .

build_script:
  - make

notifications:
  - provider: Email
    to:
      - gloomyghost@gloomyghost.com
    subject: '{{projectName}}: Build is {{status}}'
    message: "
    {{projectName}} Build is {{status}}<br/>
    {{#passed}}
        <h1 style=\"font-size: 150%;font-weight:normal; color:#078DC7;\">
        <a href=\"{{buildUrl}}\" style=\"color:#078DC7;\">Build {{projectName}} {{buildVersion}} completed</a>
        </h1>
        <br/>
    {{/passed}}
    {{#failed}}
        <h1 style=\"font-size: 150%;font-weight:normal; color:#ff3228;\">
        <a href=\"{{buildUrl}}\" style=\"color:#ff3228;\">Build {{projectName}} {{buildVersion}} failed</a>
        </h1>
        <br/>
    {{/failed}}
    The Message is: {{message}} (NULL WHEN SUCCESS)<br/>
    CommitID is: {{commitId}} by {{commitAuthor}} on {{commitDate}}<br/>
    Commit Message is: {{commitMessage}}
    "
    on_build_status_changed: true